### ISSUE TITLE
Only layers of same output shape can be merged using sum mode

### ISSUE THREAD

**Issue by na978292231** [ljsabc/MangaLineExtraction#1]
Dear writer,
       please tell me what's wrong in issue.I have run the code from yours without change but the result is workout.The process and error like this:
ZhonguodeMacBook-Pro:MangaLineExtraction-master zhonguoxu$ python3 test_mse.py ./Arise ./output 
Using TensorFlow backend.
Traceback (most recent call last):
  File "test_mse.py", line 85, in <module>
    test(sys.argv[1])
  File "test_mse.py", line 51, in test
    model = loadModel(home)
  File "test_mse.py", line 44, in loadModel
    model = model_from_json(loaded_model_json)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/models.py", line 210, in model_from_json
    return layer_from_config(config, custom_objects=custom_objects)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/utils/layer_utils.py", line 38, in layer_from_config
    return layer_class.from_config(config['config'], custom_objects=custom_objects)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2575, in from_config
    process_layer(layer_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 2572, in process_layer
    layer(input_tensors)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 1450, in __call__
    node_indices, tensor_indices)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/engine/topology.py", line 1329, in _arguments_validation
    'Layer shapes: %s' % input_shapes)
ValueError: Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 384, None, None), (None, 192, None, None)]
       Thank you for attention!

**Comment by q5390498** [comment]
same problem. I think it is one of the bug in Keras. Can you share the part of the code that builds the model? Thx a lot! @ljsabc

**Comment by ljsabc** [comment]
This is due to the dimension ordering in the previous version of keras. 
Please use the following keras.json:
`{
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}`

BTW, Maybe someday I will rewrite the full code in pytorch or something.

**Comment by ljsabc** [comment]
Please tell me if it works so that I can close this issue.

**Comment by q5390498** [comment]
No, I have tried to revise the keras.json, it does not works.  I converted the erika.json and weights.h5 to tensorflow format,  it works well. Thank you for your shared.

**Comment by ljsabc** [comment]
> No, I have tried to revise the keras.json, it does not works. I converted the erika.json and weights.h5 to tensorflow format, it works well. Thank you for your shared.

This is due to the internal API problem. (keras 2.0 changed the value of image_dim_ordering into something like "channels_last" or "channels_first", but for keras 1.0 I think the "th" ordering should solve this problem.)

By the way would you like to share the tf version? It may help those tf guys.

**Comment by q5390498** [comment]
My tf version is 1.4.0, keras version is 1.2.0. In erika.json, I replaced "th" to "tf", and replaced "axis=1" to "axis=3", input_dim is (null, null, null, 1), after revised json file, I converted weights.h5 to tf format, we only need transpose the convolution layer weights, for example: np.transpose(kernel, (3,2,1,0)).

**Comment by ljsabc** [comment]
> My tf version is 1.4.0, keras version is 1.2.0. In erika.json, I replaced "th" to "tf", and replaced "axis=1" to "axis=3", input_dim is (null, null, null, 1), after revised json file, I converted weights.h5 to tf format, we only need transpose the convolution layer weights, for example: np.transpose(kernel, (3,2,1,0)).

Thanks very much. Your help is appreciated.

**Comment by naoto0804** [comment]
Just in case for guys using keras with theano backend, the way @ljsabc recommended to modify `keras.json` worked when I installed the correct versions. Thank you for great work and easy-to-use open sourced codes!

**Comment by ashishgupta2598** [comment]
Thanks for the help @ljsabc . How you modify the conv weights by transposing @q5390498 . @ljsabc  I got this error after making the changes(I think because I haven't perform transpose). Please guide @ljsabc @q5390498 .
```  
Traceback (most recent call last):
  File "/home/ashish/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1864, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 3 and 24. Shapes are [3,3,1,24] and [24,1,3,3]. for 'Assign_4' (op: 'Assign') with input shapes: [3,3,1,24], [24,1,3,3].
```
