### ISSUE TITLE
Only layers of same output shape can be merged using sum mode. Layer shapes: [(None, 384, None, None), (None, 192, None, None)]

### ISSUE THREAD

**Issue by steveandrew** [ljsabc/MangaLineExtraction#8]
![Capture](https://user-images.githubusercontent.com/34563599/88263444-ab335080-cce7-11ea-994d-331621d67a37.JPG)

**Comment by DLove1204** [comment]
as same problem to you, can you fix it now?

**Comment by steveandrew** [comment]
> as same problem to you, can you fix it now?

No Brother.

**Comment by Nauhcnay** [comment]
I have solved this problem in a different way from #1.
Generally, if you install all the dependency correctly, and the method in #1 should work. However, if you still failed, then you probably have the same issue as mine.

My solution is:
add `os.environ['KERAS_BACKEND'] = "tensorflow"` after `import os`
add `K.set_image_dim_ordering('th')` after `from keras import backend as K`
in **test_mse.py**

Hope that could be helpful

**Comment by steveandrew** [comment]
> I have solved this problem in a different way from #1.
> Generally, if you install all the dependency correctly, and the method in #1 should work. However, if you still failed, then you probably have the same issue as mine.
> 
> My solution is:
> add `os.environ['KERAS_BACKEND'] = "tensorflow"` after `import os`
> add `K.set_image_dim_ordering('th')` after `from keras import backend as K`
> in **test_mse.py**
> 
> Hope that could be helpful

thankyou So much for ur effort I will try that out :)
